# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner-protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inner-protocol.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14inner-protocol.proto\"Q\n\x13SnapshotPacketInner\x12 \n\x08snapshot\x18\x01 \x01(\x0b\x32\x0e.SnapshotInner\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.UserInner\"\x98\x01\n\tUserInner\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\r\x12&\n\x06gender\x18\x04 \x01(\x0e\x32\x16.UserInner.GenderInner\".\n\x0bGenderInner\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\"\xa1\x01\n\rSnapshotInner\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\x04\x12\x18\n\x04pose\x18\x02 \x01(\x0b\x32\n.PoseInner\x12 \n\x0b\x63olor_image\x18\x03 \x01(\x0b\x32\x0b.ImageInner\x12 \n\x0b\x64\x65pth_image\x18\x04 \x01(\x0b\x32\x0b.ImageInner\x12 \n\x08\x66\x65\x65lings\x18\x05 \x01(\x0b\x32\x0e.FeelingsInner\"\xdb\x01\n\tPoseInner\x12\x30\n\x0btranslation\x18\x01 \x01(\x0b\x32\x1b.PoseInner.TranslationInner\x12*\n\x08rotation\x18\x02 \x01(\x0b\x32\x18.PoseInner.RotationInner\x1a\x33\n\x10TranslationInner\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a;\n\rRotationInner\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"<\n\nImageInner\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0f\n\x07\x62lob_id\x18\x03 \x01(\t\"V\n\rFeelingsInner\x12\x0e\n\x06hunger\x18\x01 \x01(\x02\x12\x0e\n\x06thirst\x18\x02 \x01(\x02\x12\x12\n\nexhaustion\x18\x03 \x01(\x02\x12\x11\n\thappiness\x18\x04 \x01(\x02\x62\x06proto3'
)



_USERINNER_GENDERINNER = _descriptor.EnumDescriptor(
  name='GenderInner',
  full_name='UserInner.GenderInner',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=214,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_USERINNER_GENDERINNER)


_SNAPSHOTPACKETINNER = _descriptor.Descriptor(
  name='SnapshotPacketInner',
  full_name='SnapshotPacketInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot', full_name='SnapshotPacketInner.snapshot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='SnapshotPacketInner.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=105,
)


_USERINNER = _descriptor.Descriptor(
  name='UserInner',
  full_name='UserInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserInner.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='UserInner.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='UserInner.birthday', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='UserInner.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERINNER_GENDERINNER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=260,
)


_SNAPSHOTINNER = _descriptor.Descriptor(
  name='SnapshotInner',
  full_name='SnapshotInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='SnapshotInner.datetime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='SnapshotInner.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='SnapshotInner.color_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='SnapshotInner.depth_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='SnapshotInner.feelings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=424,
)


_POSEINNER_TRANSLATIONINNER = _descriptor.Descriptor(
  name='TranslationInner',
  full_name='PoseInner.TranslationInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseInner.TranslationInner.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseInner.TranslationInner.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseInner.TranslationInner.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=585,
)

_POSEINNER_ROTATIONINNER = _descriptor.Descriptor(
  name='RotationInner',
  full_name='PoseInner.RotationInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseInner.RotationInner.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseInner.RotationInner.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseInner.RotationInner.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='PoseInner.RotationInner.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=646,
)

_POSEINNER = _descriptor.Descriptor(
  name='PoseInner',
  full_name='PoseInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='PoseInner.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='PoseInner.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSEINNER_TRANSLATIONINNER, _POSEINNER_ROTATIONINNER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=646,
)


_IMAGEINNER = _descriptor.Descriptor(
  name='ImageInner',
  full_name='ImageInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ImageInner.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ImageInner.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob_id', full_name='ImageInner.blob_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=708,
)


_FEELINGSINNER = _descriptor.Descriptor(
  name='FeelingsInner',
  full_name='FeelingsInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='FeelingsInner.hunger', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='FeelingsInner.thirst', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='FeelingsInner.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='FeelingsInner.happiness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=796,
)

_SNAPSHOTPACKETINNER.fields_by_name['snapshot'].message_type = _SNAPSHOTINNER
_SNAPSHOTPACKETINNER.fields_by_name['user'].message_type = _USERINNER
_USERINNER.fields_by_name['gender'].enum_type = _USERINNER_GENDERINNER
_USERINNER_GENDERINNER.containing_type = _USERINNER
_SNAPSHOTINNER.fields_by_name['pose'].message_type = _POSEINNER
_SNAPSHOTINNER.fields_by_name['color_image'].message_type = _IMAGEINNER
_SNAPSHOTINNER.fields_by_name['depth_image'].message_type = _IMAGEINNER
_SNAPSHOTINNER.fields_by_name['feelings'].message_type = _FEELINGSINNER
_POSEINNER_TRANSLATIONINNER.containing_type = _POSEINNER
_POSEINNER_ROTATIONINNER.containing_type = _POSEINNER
_POSEINNER.fields_by_name['translation'].message_type = _POSEINNER_TRANSLATIONINNER
_POSEINNER.fields_by_name['rotation'].message_type = _POSEINNER_ROTATIONINNER
DESCRIPTOR.message_types_by_name['SnapshotPacketInner'] = _SNAPSHOTPACKETINNER
DESCRIPTOR.message_types_by_name['UserInner'] = _USERINNER
DESCRIPTOR.message_types_by_name['SnapshotInner'] = _SNAPSHOTINNER
DESCRIPTOR.message_types_by_name['PoseInner'] = _POSEINNER
DESCRIPTOR.message_types_by_name['ImageInner'] = _IMAGEINNER
DESCRIPTOR.message_types_by_name['FeelingsInner'] = _FEELINGSINNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotPacketInner = _reflection.GeneratedProtocolMessageType('SnapshotPacketInner', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTPACKETINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotPacketInner)
  })
_sym_db.RegisterMessage(SnapshotPacketInner)

UserInner = _reflection.GeneratedProtocolMessageType('UserInner', (_message.Message,), {
  'DESCRIPTOR' : _USERINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:UserInner)
  })
_sym_db.RegisterMessage(UserInner)

SnapshotInner = _reflection.GeneratedProtocolMessageType('SnapshotInner', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotInner)
  })
_sym_db.RegisterMessage(SnapshotInner)

PoseInner = _reflection.GeneratedProtocolMessageType('PoseInner', (_message.Message,), {

  'TranslationInner' : _reflection.GeneratedProtocolMessageType('TranslationInner', (_message.Message,), {
    'DESCRIPTOR' : _POSEINNER_TRANSLATIONINNER,
    '__module__' : 'inner_protocol_pb2'
    # @@protoc_insertion_point(class_scope:PoseInner.TranslationInner)
    })
  ,

  'RotationInner' : _reflection.GeneratedProtocolMessageType('RotationInner', (_message.Message,), {
    'DESCRIPTOR' : _POSEINNER_ROTATIONINNER,
    '__module__' : 'inner_protocol_pb2'
    # @@protoc_insertion_point(class_scope:PoseInner.RotationInner)
    })
  ,
  'DESCRIPTOR' : _POSEINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:PoseInner)
  })
_sym_db.RegisterMessage(PoseInner)
_sym_db.RegisterMessage(PoseInner.TranslationInner)
_sym_db.RegisterMessage(PoseInner.RotationInner)

ImageInner = _reflection.GeneratedProtocolMessageType('ImageInner', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:ImageInner)
  })
_sym_db.RegisterMessage(ImageInner)

FeelingsInner = _reflection.GeneratedProtocolMessageType('FeelingsInner', (_message.Message,), {
  'DESCRIPTOR' : _FEELINGSINNER,
  '__module__' : 'inner_protocol_pb2'
  # @@protoc_insertion_point(class_scope:FeelingsInner)
  })
_sym_db.RegisterMessage(FeelingsInner)


# @@protoc_insertion_point(module_scope)
