# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection-protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connection-protocol.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19\x63onnection-protocol.proto\"f\n\x1aSnapshotPacketCommunicated\x12\'\n\x08snapshot\x18\x01 \x01(\x0b\x32\x15.SnapshotCommunicated\x12\x1f\n\x04user\x18\x02 \x01(\x0b\x32\x11.UserCommunicated\"\xb4\x01\n\x10UserCommunicated\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\r\x12\x34\n\x06gender\x18\x04 \x01(\x0e\x32$.UserCommunicated.GenderCommunicated\"5\n\x12GenderCommunicated\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\"\xce\x01\n\x14SnapshotCommunicated\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\x04\x12\x1f\n\x04pose\x18\x02 \x01(\x0b\x32\x11.PoseCommunicated\x12,\n\x0b\x63olor_image\x18\x03 \x01(\x0b\x32\x17.ColorImageCommunicated\x12,\n\x0b\x64\x65pth_image\x18\x04 \x01(\x0b\x32\x17.DepthImageCommunicated\x12\'\n\x08\x66\x65\x65lings\x18\x05 \x01(\x0b\x32\x15.FeelingsCommunicated\"\x8c\x02\n\x10PoseCommunicated\x12>\n\x0btranslation\x18\x01 \x01(\x0b\x32).PoseCommunicated.TranslationCommunicated\x12\x38\n\x08rotation\x18\x02 \x01(\x0b\x32&.PoseCommunicated.RotationCommunicated\x1a:\n\x17TranslationCommunicated\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x42\n\x14RotationCommunicated\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"E\n\x16\x43olorImageCommunicated\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"E\n\x16\x44\x65pthImageCommunicated\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"]\n\x14\x46\x65\x65lingsCommunicated\x12\x0e\n\x06hunger\x18\x01 \x01(\x02\x12\x0e\n\x06thirst\x18\x02 \x01(\x02\x12\x12\n\nexhaustion\x18\x03 \x01(\x02\x12\x11\n\thappiness\x18\x04 \x01(\x02\x62\x06proto3'
)



_USERCOMMUNICATED_GENDERCOMMUNICATED = _descriptor.EnumDescriptor(
  name='GenderCommunicated',
  full_name='UserCommunicated.GenderCommunicated',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=261,
  serialized_end=314,
)
_sym_db.RegisterEnumDescriptor(_USERCOMMUNICATED_GENDERCOMMUNICATED)


_SNAPSHOTPACKETCOMMUNICATED = _descriptor.Descriptor(
  name='SnapshotPacketCommunicated',
  full_name='SnapshotPacketCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot', full_name='SnapshotPacketCommunicated.snapshot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='SnapshotPacketCommunicated.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=131,
)


_USERCOMMUNICATED = _descriptor.Descriptor(
  name='UserCommunicated',
  full_name='UserCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserCommunicated.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='UserCommunicated.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='UserCommunicated.birthday', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='UserCommunicated.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERCOMMUNICATED_GENDERCOMMUNICATED,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=314,
)


_SNAPSHOTCOMMUNICATED = _descriptor.Descriptor(
  name='SnapshotCommunicated',
  full_name='SnapshotCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='SnapshotCommunicated.datetime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='SnapshotCommunicated.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='SnapshotCommunicated.color_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='SnapshotCommunicated.depth_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='SnapshotCommunicated.feelings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=523,
)


_POSECOMMUNICATED_TRANSLATIONCOMMUNICATED = _descriptor.Descriptor(
  name='TranslationCommunicated',
  full_name='PoseCommunicated.TranslationCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseCommunicated.TranslationCommunicated.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseCommunicated.TranslationCommunicated.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseCommunicated.TranslationCommunicated.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=726,
)

_POSECOMMUNICATED_ROTATIONCOMMUNICATED = _descriptor.Descriptor(
  name='RotationCommunicated',
  full_name='PoseCommunicated.RotationCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseCommunicated.RotationCommunicated.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseCommunicated.RotationCommunicated.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseCommunicated.RotationCommunicated.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='PoseCommunicated.RotationCommunicated.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=728,
  serialized_end=794,
)

_POSECOMMUNICATED = _descriptor.Descriptor(
  name='PoseCommunicated',
  full_name='PoseCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='PoseCommunicated.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='PoseCommunicated.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSECOMMUNICATED_TRANSLATIONCOMMUNICATED, _POSECOMMUNICATED_ROTATIONCOMMUNICATED, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=794,
)


_COLORIMAGECOMMUNICATED = _descriptor.Descriptor(
  name='ColorImageCommunicated',
  full_name='ColorImageCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ColorImageCommunicated.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ColorImageCommunicated.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ColorImageCommunicated.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=796,
  serialized_end=865,
)


_DEPTHIMAGECOMMUNICATED = _descriptor.Descriptor(
  name='DepthImageCommunicated',
  full_name='DepthImageCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='DepthImageCommunicated.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='DepthImageCommunicated.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DepthImageCommunicated.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=867,
  serialized_end=936,
)


_FEELINGSCOMMUNICATED = _descriptor.Descriptor(
  name='FeelingsCommunicated',
  full_name='FeelingsCommunicated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='FeelingsCommunicated.hunger', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='FeelingsCommunicated.thirst', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='FeelingsCommunicated.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='FeelingsCommunicated.happiness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=938,
  serialized_end=1031,
)

_SNAPSHOTPACKETCOMMUNICATED.fields_by_name['snapshot'].message_type = _SNAPSHOTCOMMUNICATED
_SNAPSHOTPACKETCOMMUNICATED.fields_by_name['user'].message_type = _USERCOMMUNICATED
_USERCOMMUNICATED.fields_by_name['gender'].enum_type = _USERCOMMUNICATED_GENDERCOMMUNICATED
_USERCOMMUNICATED_GENDERCOMMUNICATED.containing_type = _USERCOMMUNICATED
_SNAPSHOTCOMMUNICATED.fields_by_name['pose'].message_type = _POSECOMMUNICATED
_SNAPSHOTCOMMUNICATED.fields_by_name['color_image'].message_type = _COLORIMAGECOMMUNICATED
_SNAPSHOTCOMMUNICATED.fields_by_name['depth_image'].message_type = _DEPTHIMAGECOMMUNICATED
_SNAPSHOTCOMMUNICATED.fields_by_name['feelings'].message_type = _FEELINGSCOMMUNICATED
_POSECOMMUNICATED_TRANSLATIONCOMMUNICATED.containing_type = _POSECOMMUNICATED
_POSECOMMUNICATED_ROTATIONCOMMUNICATED.containing_type = _POSECOMMUNICATED
_POSECOMMUNICATED.fields_by_name['translation'].message_type = _POSECOMMUNICATED_TRANSLATIONCOMMUNICATED
_POSECOMMUNICATED.fields_by_name['rotation'].message_type = _POSECOMMUNICATED_ROTATIONCOMMUNICATED
DESCRIPTOR.message_types_by_name['SnapshotPacketCommunicated'] = _SNAPSHOTPACKETCOMMUNICATED
DESCRIPTOR.message_types_by_name['UserCommunicated'] = _USERCOMMUNICATED
DESCRIPTOR.message_types_by_name['SnapshotCommunicated'] = _SNAPSHOTCOMMUNICATED
DESCRIPTOR.message_types_by_name['PoseCommunicated'] = _POSECOMMUNICATED
DESCRIPTOR.message_types_by_name['ColorImageCommunicated'] = _COLORIMAGECOMMUNICATED
DESCRIPTOR.message_types_by_name['DepthImageCommunicated'] = _DEPTHIMAGECOMMUNICATED
DESCRIPTOR.message_types_by_name['FeelingsCommunicated'] = _FEELINGSCOMMUNICATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotPacketCommunicated = _reflection.GeneratedProtocolMessageType('SnapshotPacketCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTPACKETCOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotPacketCommunicated)
  })
_sym_db.RegisterMessage(SnapshotPacketCommunicated)

UserCommunicated = _reflection.GeneratedProtocolMessageType('UserCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _USERCOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:UserCommunicated)
  })
_sym_db.RegisterMessage(UserCommunicated)

SnapshotCommunicated = _reflection.GeneratedProtocolMessageType('SnapshotCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTCOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotCommunicated)
  })
_sym_db.RegisterMessage(SnapshotCommunicated)

PoseCommunicated = _reflection.GeneratedProtocolMessageType('PoseCommunicated', (_message.Message,), {

  'TranslationCommunicated' : _reflection.GeneratedProtocolMessageType('TranslationCommunicated', (_message.Message,), {
    'DESCRIPTOR' : _POSECOMMUNICATED_TRANSLATIONCOMMUNICATED,
    '__module__' : 'connection_protocol_pb2'
    # @@protoc_insertion_point(class_scope:PoseCommunicated.TranslationCommunicated)
    })
  ,

  'RotationCommunicated' : _reflection.GeneratedProtocolMessageType('RotationCommunicated', (_message.Message,), {
    'DESCRIPTOR' : _POSECOMMUNICATED_ROTATIONCOMMUNICATED,
    '__module__' : 'connection_protocol_pb2'
    # @@protoc_insertion_point(class_scope:PoseCommunicated.RotationCommunicated)
    })
  ,
  'DESCRIPTOR' : _POSECOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:PoseCommunicated)
  })
_sym_db.RegisterMessage(PoseCommunicated)
_sym_db.RegisterMessage(PoseCommunicated.TranslationCommunicated)
_sym_db.RegisterMessage(PoseCommunicated.RotationCommunicated)

ColorImageCommunicated = _reflection.GeneratedProtocolMessageType('ColorImageCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _COLORIMAGECOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:ColorImageCommunicated)
  })
_sym_db.RegisterMessage(ColorImageCommunicated)

DepthImageCommunicated = _reflection.GeneratedProtocolMessageType('DepthImageCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHIMAGECOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:DepthImageCommunicated)
  })
_sym_db.RegisterMessage(DepthImageCommunicated)

FeelingsCommunicated = _reflection.GeneratedProtocolMessageType('FeelingsCommunicated', (_message.Message,), {
  'DESCRIPTOR' : _FEELINGSCOMMUNICATED,
  '__module__' : 'connection_protocol_pb2'
  # @@protoc_insertion_point(class_scope:FeelingsCommunicated)
  })
_sym_db.RegisterMessage(FeelingsCommunicated)


# @@protoc_insertion_point(module_scope)
